description: >
  This is a sample executor using Docker and Node.
docker:
  - image: 'aeternity/image:<<parameters.tag>>'
parameters:
  tag:
    default: v2.12.4
    description: >
      ae build tag
    type: string
